services:
  database:
    image: mysql
    container_name: honorbox-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql

  redis:
    image: redis
    container_name: honorbox-redis
    restart: unless-stopped
    ports:
      - 6379:6379
